x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  restart: always
  env_file:
    - .env
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__CORE__LOAD_DEFAULT_CONNECTIONS: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/${AIRFLOW_DB_NAME}
    AIRFLOW__LOGGING__BASE_LOG_FOLDER: /opt/airflow/logs
    AIRFLOW__LOGGING__DAG_PROCESSOR_MANAGER_LOG_LOCATION: /opt/airflow/logs/dag_processor_manager/dag_processor_manager.log
  volumes:
    - ./:/opt/airflow  # Mount entire project
    - ./requirements.txt:/requirements.txt
  user: "${AIRFLOW_UID:-50000}"

services:
  airflow-db:
    image: postgres:13
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    depends_on:
      - airflow-db
      - scheduler
    command: >
      bash -c '
        pip install --no-cache-dir -r /requirements.txt && \
        if [ ! -f /opt/airflow/airflow.db.inited ]; then
          airflow db migrate && \
          airflow users create \
            --username airflow \
            --firstname Airflow \
            --lastname Admin \
            --role Admin \
            --email airflow@example.com \
            --password airflow && \
          touch /opt/airflow/airflow.db.inited;
        fi && \
        airflow webserver
      '

  scheduler:
    <<: *airflow-common
    command: >
      bash -c "
        pip install --no-cache-dir -r /requirements.txt && \
        airflow scheduler
      "

  pgdb:
    image: postgres:14
    container_name: pgdb
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${MARKETING_DB_USER}
      POSTGRES_PASSWORD: ${MARKETING_DB_PASSWORD}
      POSTGRES_DB: ${MARKETING_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  airflow_db_data:
  pgdata: