version: '3'

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${AIRFLOW_DB_USER}:${AIRFLOW_DB_PASSWORD}@airflow-db:5432/${AIRFLOW_DB_NAME}
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW_UID: ${AIRFLOW_UID}
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/requirements.txt
  depends_on:
    - airflow-db

services:

  airflow-db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${AIRFLOW_DB_USER}
      POSTGRES_PASSWORD: ${AIRFLOW_DB_PASSWORD}
      POSTGRES_DB: ${AIRFLOW_DB_NAME}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      if [ ! -f /opt/airflow/airflow.db.inited ]; then
        airflow db init &&
        airflow users create --username ${AIRFLOW_ADMIN_USERNAME} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Bita --lastname Ashoori --role Admin --email bita@example.com &&
        touch /opt/airflow/airflow.db.inited;
      fi &&
      airflow webserver
      "

  scheduler:
    <<: *airflow-common
    command: >
      bash -c "
      pip install --no-cache-dir -r /requirements.txt &&
      airflow scheduler
      "

volumes:
  postgres-db-volume: