version: "3.8"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  restart: always
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@airflow-db:5432/airflow
  volumes:
    - ./airflow/dags:/opt/airflow/dags
    - ./airflow/logs:/opt/airflow/logs
    - ./airflow/plugins:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}"

services:
  airflow-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - airflow_db_data:/var/lib/postgresql/data

  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: >
      bash -c "
      if [ ! -f /opt/airflow/airflow.db.inited ]; then
          airflow db init &&
          airflow users create \
              --username airflow \
              --firstname Airflow \
              --lastname Admin \
              --role Admin \
              --email airflow@example.com \
              --password airflow &&
          touch /opt/airflow/airflow.db.inited;
      fi &&
      airflow webserver
      "
    depends_on:
      - airflow-db
      - scheduler

  scheduler:
    <<: *airflow-common
    command: airflow scheduler
    depends_on:
      - airflow-db

  pgdb:
    image: postgres:14
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: marketingdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  airflow_db_data:
  pgdata: