version: '3.8'

services:
  db:
    image: postgres:14
    container_name: pgdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: marketingdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: