version: "3.8"

x-airflow-common:
  &airflow-common
  image: apache/airflow:2.7.1
  restart: always
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres:5432/airflow
  volumes:
    - ./dags:/opt/airflow/dags        # ← مطمئن شوید مسیر درست است
    - ./logs:/opt/airflow/logs
  user: "${AIRFLOW_UID:-50000}"

services:
  # ------------------------- Database ----------------------------
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - postgres_db:/var/lib/postgresql/data

  # ------------------------- Airflow Webserver -------------------
  webserver:
    <<: *airflow-common
    ports:
      - "8080:8080"
    command: >
      bash -c "
      if [ ! -f /opt/airflow/airflow.db.inited ]; then
          airflow db init &&
          airflow users create \
              --username airflow \
              --firstname Airflow \
              --lastname Admin \
              --role Admin \
              --email airflow@example.com \
              --password airflow &&
          touch /opt/airflow/airflow.db.inited;
      fi &&
      airflow webserver
      "
    depends_on:
      - postgres
      - scheduler

  # ------------------------- Airflow Scheduler -------------------
  scheduler:
    <<: *airflow-common
    command: airflow scheduler
    depends_on:
      - postgres

volumes:
  postgres_db: